# Generated by Django 6.0.3 on 2026-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(default='unknown@email.com', max_length=254),
        ),
    ]
