# Generated by Django 6.0.3 on 2026-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emergencycontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangerlocation',
            name='place_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
