# Generated by Django 6.0.3 on 2026-03-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_livelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livelocation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='livelocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
