# Generated by Django 6.0.4 on 2026-04-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_livelocation_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dangerlocation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dangerlocation",
            name="place_name",
        ),
        migrations.AddField(
            model_name="dangerlocation",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
